### ISSUE TITLE
EquivalencyTech no longer working.

### ISSUE THREAD

**Issue by Sal97c** [Sefiraat/EquivalencyTech#12]
Hi So not sure what happened, but over night ET stopped working.  Attached is my Log of the error for ET.

[13:00:56] [Server thread/INFO]: [EquivalencyTech] Enabling EquivalencyTech v1.1.5
[13:00:56] [Server thread/INFO]: [EquivalencyTech] ########################################
[13:00:56] [Server thread/INFO]: [EquivalencyTech]              EquivalencyTech            
[13:00:56] [Server thread/INFO]: [EquivalencyTech]            Created by Sefiraat          
[13:00:56] [Server thread/INFO]: [EquivalencyTech] ########################################
[13:00:56] [Server thread/ERROR]: Error occurred while enabling EquivalencyTech v1.1.5 (Is it up to date?)
java.lang.NoClassDefFoundError: me/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem
	at io.github.sefiraat.equivalencytech.misc.ManagerSupportedPlugins.slimefun(ManagerSupportedPlugins.java:35) ~[EquivalencyTech-1.1.5.jar:?]
	at io.github.sefiraat.equivalencytech.misc.ManagerSupportedPlugins.<init>(ManagerSupportedPlugins.java:28) ~[EquivalencyTech-1.1.5.jar:?]
	at io.github.sefiraat.equivalencytech.EquivalencyTech.onEnable(EquivalencyTech.java:92) ~[EquivalencyTech-1.1.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Paper-157]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-157]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-157]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:529) ~[patched_1.17.1.jar:git-Paper-157]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:443) ~[patched_1.17.1.jar:git-Paper-157]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639) ~[patched_1.17.1.jar:git-Paper-157]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-157]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-157]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-157]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: me.mrCookieSlime.Slimefun.Objects.SlimefunItem.SlimefunItem
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[patched_1.17.1.jar:git-Paper-157]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-157]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 13 more
[13:00:56] [Server thread/INFO]: [EquivalencyTech] Disabling EquivalencyTech v1.1.5

**Comment by Sefiraat** [comment]
Grab the latest update from the releases :). The most recent slimefun build(s) introduced a new series of breaking changes that required an update. When you do this, all should work fine. Reopen if not! :D

**Comment by Sal97c** [comment]
Hi, Still didn't work, Where is the latest release? I checked spigot and the Github but they are still the 1.1.5

**Comment by Sefiraat** [comment]
It’s on the releases section of this GitHub :)
https://github.com/Sefiraat/EquivalencyTech/releases
