### ISSUE TITLE
Condensate Chest broke and server console getting spammed with errors

### ISSUE THREAD

**Issue by l-Cai-l** [Sefiraat/EquivalencyTech#34]
## What caused the issue, what steps led up to the issue (Mandatory)

The only thing that i have done was break one of these with an explosive pick, idk if that had anything to do with it though.
## Log of error, if applicable
[16:36:38 WARN]: [EquivalencyTech] Task #30 for EquivalencyTech v1.1.6 generated an exception
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_18_R1.block.CraftBlockState cannot be cast to class org.bukkit.block.Chest (org.bukkit.craftbukkit.v1_18_R1.block.CraftBlockState and org.bukkit.block.Chest are in unnamed module of loader java.net.URLClassLoader @504bae78)
        at io.github.sefiraat.equivalencytech.runnables.RunnableEQTick.processCChests(RunnableEQTick.java:75) ~[EquivalencyTech-1.1.6.jar:?]
        at io.github.sefiraat.equivalencytech.runnables.RunnableEQTick.run(RunnableEQTick.java:30) ~[EquivalencyTech-1.1.6.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-133]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-133]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-133]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-133]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-133]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-133]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-133]
## Server Type and version (Spigot/Paper etc.)
Paperspigot 1.18.1 133
## Minecraft version
1.18.1

**Comment by SlickTorpedo** [comment]
I'm having this issue too

**Comment by SlickTorpedo** [comment]
[11:30:22 WARN]: [EquivalencyTech] Task #85 for EquivalencyTech v1.1.6 generated an exception
java.lang.ClassCastException: null

I'm also getting this issue every like second in console. Just look like this:
![image](https://user-images.githubusercontent.com/55722867/151401651-302e2f2e-9089-475d-95c6-aa44ba83d176.png)

**Comment by Sefiraat** [comment]
The issue happens when a condensate chest is destroyed in a way I am not checking for. You can remove the offending chest from the condensation_chests.yml. I have just pushed an update that will change this error to something more useful for you to be able to track down the source and resolve - though the actual issue will still remain and that will await the merging of EMC2 + Equitech later on.
