### ISSUE TITLE
[Issue]Dissolution Chest doesn't work

### ISSUE THREAD

**Issue by ifloppy** [Sefiraat/EquivalencyTech#44]
## Description (Mandatory)

Dissolution Chest doesn't consume all given items and convert them into EMC

## What caused the issue, what steps led up to the issue (Mandatory)

Players are using a lot of Dissolution Chest, I don't know other things about this

## Log of error, if applicable

[15:59:12] [Server thread/WARN]: [EquivalencyTech] Task #40 for EquivalencyTech v1.1.6 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "io.github.sefiraat.equivalencytech.misc.Utils.getEMC(io.github.sefiraat.equivalencytech.EquivalencyTech, org.bukkit.inventory.ItemStack)" is null
	at io.github.sefiraat.equivalencytech.runnables.RunnableEQTick.processDChests(RunnableEQTick.java:47) ~[EquivalencyTech-1.1.6.jar:?]
	at io.github.sefiraat.equivalencytech.runnables.RunnableEQTick.run(RunnableEQTick.java:29) ~[EquivalencyTech-1.1.6.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-257]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-257]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1531) ~[paper-1.18.2.jar:git-Paper-257]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-257]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-257]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-257]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-257]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:59:13] [Server thread/WARN]: [EquivalencyTech] Task #40 for EquivalencyTech v1.1.6 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "io.github.sefiraat.equivalencytech.misc.Utils.getEMC(io.github.sefiraat.equivalencytech.EquivalencyTech, org.bukkit.inventory.ItemStack)" is null
	at io.github.sefiraat.equivalencytech.runnables.RunnableEQTick.processDChests(RunnableEQTick.java:47) ~[EquivalencyTech-1.1.6.jar:?]
	at io.github.sefiraat.equivalencytech.runnables.RunnableEQTick.run(RunnableEQTick.java:29) ~[EquivalencyTech-1.1.6.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-257]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-257]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1531) ~[paper-1.18.2.jar:git-Paper-257]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-257]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-257]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-257]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-257]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:59:14] [Server thread/WARN]: [EquivalencyTech] Task #40 for EquivalencyTech v1.1.6 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "io.github.sefiraat.equivalencytech.misc.Utils.getEMC(io.github.sefiraat.equivalencytech.EquivalencyTech, org.bukkit.inventory.ItemStack)" is null
	at io.github.sefiraat.equivalencytech.runnables.RunnableEQTick.processDChests(RunnableEQTick.java:47) ~[EquivalencyTech-1.1.6.jar:?]
	at io.github.sefiraat.equivalencytech.runnables.RunnableEQTick.run(RunnableEQTick.java:29) ~[EquivalencyTech-1.1.6.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-257]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-257]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1531) ~[paper-1.18.2.jar:git-Paper-257]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-257]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-257]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-257]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-257]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

## Server Type and version (Spigot/Paper etc.)

The latest version of Paper (1.18.2-257)

## Minecraft version

1.18..2

**Comment by ifloppy** [comment]
我尝试去解决问题，检查了服务器中所有的溶解箱，最终发现把一个没有设置EMC价值的物品放入溶解箱会导致整个服务器中所有溶解箱都不能正常工作。
这是我在某玩家做的垃圾桶中找到的
![image](https://user-images.githubusercontent.com/68799904/158936678-d0dd53b8-ab0e-495b-82b8-5bded6efe19a.png)

**Comment by Zynax1** [comment]
I am also having this issue
