### ISSUE TITLE
Flooding on console

### ISSUE THREAD

**Issue by pump61** [Sefiraat/EquivalencyTech#7]
[21:58:11 WARN]: [EquivalencyTech] Task #136 for EquivalencyTech v1.1.5 generated an exception
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_16_R3.block.CraftSkull cannot be cast to class org.bukkit.block.Chest (org.bukkit.craftbukkit.v1_16_R3.block.CraftSkull and org.bukkit.block.Chest are in unnamed module of loader 'app')
at io.github.sefiraat.equivalencytech.runnables.RunnableEQTick.processDChests(RunnableEQTick.java:37) ~[?:?]
at io.github.sefiraat.equivalencytech.runnables.RunnableEQTick.run(RunnableEQTick.java:29) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1171]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1171]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1503) ~[patched_1.16.5.jar:git-Purpur-1171]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1171]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1171]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
at java.lang.Thread.run(Thread.java:834) [?:?]

Purpur git-Purpur-1171 (MC: 1.16.5)
Slimefun DEV - 943 (git 51bfbbd6)
Metrics-Module #25
Java 11
Installed Addons: (25)
ExtraTools vDEV - 28 (git 58488a2e)
FoxyMachines vDEV - 45 (git ce4f8193)
SlimefunOreChunks vDEV - 13 (git 9f7a2be3)
DynaTech vDEV - 122 (git ed16c149)
ExtraGear vDEV - 12 (git 4570ea2c)
ClayTech vviolet-1.2.24
CMILib v1.0.2.6
InfinityExpansion vDEV - 114 (git 9d5d3cec)
ElectricSpawners vDEV - 22 (git 4cb2c56b)
EMC2 vDEV - 5 (git 5a315e2c)
MobCapturer vDEV - 15 (git a42c9e0c)
SlimyTreeTaps vDEV - 19 (git 69930ef7)
SlimeTinker vDEV - 17 (git adbc5779)
TranscEndence vDEV - 34 (git eece87db)
FluffyMachines vDEV - 85 (git 037a45b8)
ChestTerminal vDEV - 43 (git 3096bab5)
DyedBackpacks vDEV - 16 (git 20d28ccc)
AlchimiaVitae vDEV - 5 (git 0a8287f0)
EcoPower vDEV - 4 (git 2a08d31d)
ExoticGarden vDEV - 76 (git d148a362)
Liquid vDEV - 12 (git b7a6c543)
LiteXpansion vDEV - 153 (git a9a97232)
SimpleUtils vDEV - 9 (git 7f454341)
SoulJars vDEV - 22 (git aded79dd)
EquivalencyTech v1.1.5

**Comment by Sefiraat** [comment]
Hi Pump, I did mention this in discord but I really need to know what you were doing with the Dissolution chest both before and after these errors started.
